# docker-compose.yml
version: '3'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: logparser_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8081
    volumes:
      - .:/app
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  postgres_data: